test job

diff --git a/.github/workflows/temp.yml b/.github/workflows/temp.yml
--- a/.github/workflows/temp.yml
+++ b/.github/workflows/temp.yml
@@ -40,3 +40,37 @@ jobs:
           project_id: ${{ secrets.GKE_PROTOCOL_PROJECT }}
       
       - run: kubectl get jobs
+
+      - name: Template Kubernetes Job Manifest
+        env:
+          GITHUB_ISSUE: ${{ github.event.number }}
+          COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
+        run: |
+          envsubst < .github/workflows-helpers/run-e2e-test-job-template.yaml > job.yaml
+
+          kubectl apply -f job.yaml
+
+          NAMESPACE=devnet-issue-${GITHUB_ISSUE}
+          JOB_NAME=run-e2e-test
+
+          # Wait for the pod to be created
+          while [[ -z $(kubectl get pods -n ${NAMESPACE} --selector=job-name=${JOB_NAME} -o jsonpath='{.items[0].metadata.name}') ]]; do
+            echo "Waiting for the pod to be created..."
+            sleep 5
+          done
+
+          # Get the pod name
+          POD_NAME=$(kubectl get pods -n ${NAMESPACE} --selector=job-name=${JOB_NAME} -o jsonpath='{.items[0].metadata.name}')
+
+          # Stream the pod logs
+          kubectl logs -f ${POD_NAME} -n ${NAMESPACE}
+
+          # Check the job status after the logs finish streaming
+          if ! kubectl wait --for=condition=complete --timeout=600s job/${JOB_NAME} -n ${NAMESPACE}; then
+            echo "Job failed"
+
+            kubectl delete job ${JOB_NAME} -n ${NAMESPACE}
+            exit 1
+          fi
+
+          kubectl delete job ${JOB_NAME} -n ${NAMESPACE}
