fail fast

diff --git a/.github/workflows/temp.yml b/.github/workflows/temp.yml
--- a/.github/workflows/temp.yml
+++ b/.github/workflows/temp.yml
@@ -63,11 +63,10 @@ jobs:
               echo "Ready pod found: ${READY_POD}"
               break
             else
-              echo "No ready pod with the image SHA ${IMAGE_SHA} found. Waiting..."
+              echo "Sequencer with with an image ${IMAGE_SHA} is not ready yet. Waiting..."
               sleep 10
             fi
           done
-
 
       - name: Run E2E test job
         env:
@@ -82,23 +81,33 @@ jobs:
           # Wait for the pod to be created and be in a running state
           echo "Waiting for the pod to be in the running state..."
           while : ; do
-            POD_NAME=$(kubectl get pods -n ${NAMESPACE} --selector=job-name=${JOB_NAME} -o jsonpath='{.items[0].metadata.name}')
+            POD_NAME=$(kubectl get pods -n ${NAMESPACE} --selector=job-name=${JOB_NAME} -o jsonpath='{.items[*].metadata.name}')
+            [[ -z "${POD_NAME}" ]] && echo "Waiting for pod to be scheduled..." && sleep 5 && continue
             POD_STATUS=$(kubectl get pod ${POD_NAME} -n ${NAMESPACE} -o jsonpath='{.status.phase}')
             [[ "${POD_STATUS}" == "Running" ]] && break
             echo "Current pod status: ${POD_STATUS}"
             sleep 5
           done
 
-          echo "Pod is running. Streaming logs..."
-          # Stream the pod logs
-          kubectl logs -f ${POD_NAME} -n ${NAMESPACE}
+          echo "Pod is running. Monitoring logs and status..."
+          # Stream the pod logs in the background
+          kubectl logs -f ${POD_NAME} -n ${NAMESPACE} &
 
-          # Check the job status after the logs finish streaming
-          if ! kubectl wait --for=condition=complete --timeout=600s job/${JOB_NAME} -n ${NAMESPACE}; then
-            echo "Job failed"
+          # Monitor pod status in a loop
+          while : ; do
+            CURRENT_STATUS=$(kubectl get pod ${POD_NAME} -n ${NAMESPACE} -o jsonpath="{.status.containerStatuses[0].state}")
+            if echo $CURRENT_STATUS | grep -q 'terminated'; then
+              EXIT_CODE=$(echo $CURRENT_STATUS | jq '.terminated.exitCode')
+              if [[ "$EXIT_CODE" != "0" ]]; then
+                echo "Container terminated with exit code ${EXIT_CODE}"
+                kubectl delete job ${JOB_NAME} -n ${NAMESPACE}
+                exit 1
+              fi
+              break
+            fi
+            sleep 5
+          done
 
-            kubectl delete job ${JOB_NAME} -n ${NAMESPACE}
-            exit 1
-          fi
-
+          # If the loop exits without failure, the job succeeded
+          echo "Job completed successfully"
           kubectl delete job ${JOB_NAME} -n ${NAMESPACE}
